const STATUS = {
  ACTIVE: STATUS.ACTIVE,
  INACTIVE: "INACTIVE",
  PENDING: "PENDING",
  PARTIAL: "PARTIAL",
  PAID: "PAID",
  FAILED: "FAILED",
  FROZEN: "FROZEN",
  ARCHIVED: "ARCHIVED",
  DELETED: "DELETED",
};

module.exports = STATUS;
